apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p61hqpvhc-python 
  janus-idp.io/tekton: p61hqpvhc-python
  backstage.io/kubernetes-id: p61hqpvhc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p61hqpvhc-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  